name=input("What is your name?")
print("hello,"+name+"!")
input("Press <enter>")
print(1233)
print(type(12))
a=str(True)
print(a)
print("哈哈"*100)
b=1
print(type(b))
print(type(str(b)))
print(1==1 and 1==2)
xxx=[1,2,3,4,"hh","王二","王二","王二","王二","王二"]
print(xxx)
print(xxx.count("王二"))
xxx.remove(2)
print(xxx)
